"""initial schema

Revision ID: fd5a53acec91
Revises:
Create Date: 2026-08-21 18:57:28.155321

==========================================================
THE SCHEMA AS IT STOOD AT PHASE 11.3
==========================================================

Six tables, built up across Phases 6 to 10 by
scripts/maintenance/create_job_tables.py -- a create_all()
plus a list of hand-written ALTER statements, run by hand.
That got the project here and cannot be what ships: it has no
version, no ordering, no record of what has been applied, and
no way back.

This revision is that schema, generated by autogenerating
database/models.py against an EMPTY database. Generating it
against the real one would have produced nothing, because the
real one already matches.

  document_batches   batch upload grouping
  documents          the document and its source fingerprint
  document_analyses  extraction, OCR lines, evidence,
                     confidence, dates, anomalies, quality,
                     machine decision
  document_jobs      the durable async work queue
  human_reviews      reviewer decisions and corrections
  audit_events       the audit trail


AN EXISTING DATABASE IS STAMPED, NOT UPGRADED
----------------------------------------------------------
A database that already has these tables must be marked as
already at this revision:

    alembic stamp head

Running `alembic upgrade head` against it would try to create
tables that exist and fail. Stamping records where it already
is.


THE TWO THINGS IN HERE THAT MATTER MOST
----------------------------------------------------------
1. uq_document_jobs_active_source is a PARTIAL unique index:

       UNIQUE (source_sha256) WHERE status IN
           ('QUEUED', 'PROCESSING', 'RETRY_WAIT')

   It is what makes duplicate detection race-free. Phase 10.3
   chose PostgreSQL enforcement over check-then-insert
   precisely because six simultaneous uploads of the same
   bytes cannot all lose the race. The WHERE clause is the
   whole point: identical bytes may be reprocessed once the
   earlier job has finished, but not while one is in flight.

   The status list is generated from
   backend.app.domain.job_states.ACTIVE_STATUSES so the
   index, the queries and the tests cannot disagree.

2. uq_human_reviews_document_id is a table-level UNIQUE
   constraint, not application logic. Phase 7C found
   duplicate reviews were possible through concurrent
   submission, and a constraint is the only thing that closes
   that.

Both are asserted by
tests/deployment/test_phase11_migrations.py after a real
upgrade, because an index that exists in a model and not in
the database protects nothing.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'fd5a53acec91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submitted_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_source_sha256', 'documents', ['source_sha256'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_document_id'), 'audit_events', ['document_id'], unique=False)
    op.create_table('document_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ocr_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_validation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('anomaly_validation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_analyses_document_id'), 'document_analyses', ['document_id'], unique=True)
    op.create_table('document_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=20), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('safe_error_code', sa.String(length=50), nullable=True),
    sa.Column('safe_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['document_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_jobs_batch', 'document_jobs', ['batch_id', 'status'], unique=False)
    op.create_index('ix_document_jobs_claim', 'document_jobs', ['status', 'next_attempt_at', 'created_at'], unique=False)
    op.create_index('uq_document_jobs_active_source', 'document_jobs', ['source_sha256'], unique=True, postgresql_where=sa.text("status IN ('QUEUED', 'PROCESSING', 'RETRY_WAIT')"))
    op.create_table('human_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=False),
    sa.Column('machine_decision', sa.String(length=50), nullable=True),
    sa.Column('machine_priority', sa.String(length=30), nullable=True),
    sa.Column('machine_reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('human_action', sa.String(length=30), nullable=False),
    sa.Column('corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_human_reviews_document_id')
    )
    op.create_index(op.f('ix_human_reviews_document_id'), 'human_reviews', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_reviews_document_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index('uq_document_jobs_active_source', table_name='document_jobs', postgresql_where=sa.text("status IN ('QUEUED', 'PROCESSING', 'RETRY_WAIT')"))
    op.drop_index('ix_document_jobs_claim', table_name='document_jobs')
    op.drop_index('ix_document_jobs_batch', table_name='document_jobs')
    op.drop_table('document_jobs')
    op.drop_index(op.f('ix_document_analyses_document_id'), table_name='document_analyses')
    op.drop_table('document_analyses')
    op.drop_index(op.f('ix_audit_events_document_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_documents_source_sha256', table_name='documents')
    op.drop_table('documents')
    op.drop_table('document_batches')
    # ### end Alembic commands ###
