"""worker heartbeat

Revision ID: dc2ff21970ed
Revises: fd5a53acec91
Create Date: 2026-08-21 20:02:10.024857

READ THIS BEFORE APPLYING
----------------------------------------------------------
If this file was produced by --autogenerate, check it against
what you actually changed. Autogenerate reports a RENAME as a
drop plus an add, and applying that deletes the column's data.

Then write the downgrade. An upgrade with no working downgrade
is a one-way door.
"""

from alembic import op
import sqlalchemy as sa


revision = 'dc2ff21970ed'
down_revision = 'fd5a53acec91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'RUNNING'"), nullable=False),
    sa.Column('current_job_id', sa.String(length=36), nullable=True),
    sa.Column('jobs_completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('concurrency', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index('ix_worker_heartbeats_last_seen', 'worker_heartbeats', ['last_seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worker_heartbeats_last_seen', table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    # ### end Alembic commands ###
